# Generated by Django 4.1.3 on 2022-12-14 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.CharField(max_length=13)),
                ('hours', models.CharField(max_length=12)),
                ('weeks', models.SmallIntegerField()),
                ('time', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=20)),
                ('maxnum', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.CharField(max_length=13)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=20)),
                ('credit', models.SmallIntegerField()),
                ('classroom', models.ManyToManyField(to='xk_models.classroom')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xk_models.classdetail')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xk_models.teacher')),
            ],
        ),
    ]
