# Generated by Django 4.1.4 on 2022-12-19 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.CharField(max_length=13, verbose_name='课程id')),
                ('hours', models.CharField(max_length=12, verbose_name='周学时')),
                ('weeks', models.SmallIntegerField(verbose_name='周数')),
                ('time', models.CharField(max_length=12, verbose_name='排课时间')),
                ('prerequisites', models.CharField(default=None, max_length=30, verbose_name='先修课程(分号隔开)')),
                ('teacher_info', models.CharField(default='', max_length=200, verbose_name='教师简介')),
                ('brief', models.CharField(default='', max_length=500, verbose_name='教学内容')),
                ('exam', models.CharField(choices=[('开卷考试', '开卷考试'), ('闭卷考试', '闭卷考试'), ('半开卷考试', '半开卷考试'), ('课程论文', '课程论文'), ('其他', '其他')], default='其他', max_length=10, verbose_name='考核方式')),
                ('assessment', models.CharField(default='', max_length=200, verbose_name='评分细则')),
            ],
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('classid', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='课程id')),
                ('code', models.CharField(max_length=20, verbose_name='课程编码')),
                ('name', models.CharField(max_length=30, verbose_name='课程名称')),
                ('department', models.CharField(max_length=20, verbose_name='开课院系')),
                ('credit', models.SmallIntegerField(verbose_name='学分')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=20, verbose_name='教室编号')),
                ('maxnum', models.SmallIntegerField(verbose_name='最大容量')),
            ],
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=30, verbose_name='专业')),
                ('grade', models.SmallIntegerField(verbose_name='年级')),
                ('advice', models.CharField(max_length=30, verbose_name='建议课程')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='号码')),
                ('name', models.CharField(max_length=128, verbose_name='名字')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('is_student', models.BooleanField(default=False, verbose_name='是否为学生')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='是否为老师')),
                ('is_roomadmin', models.BooleanField(default=False, verbose_name='是否为教室管理员')),
                ('is_classadmin', models.BooleanField(default=False, verbose_name='是否为教务')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='xk_models.user', verbose_name='学号')),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='入校年份')),
                ('grade', models.SmallIntegerField(verbose_name='年级')),
                ('major', models.CharField(max_length=30, verbose_name='专业')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='xk_models.user', verbose_name='工号')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('title', models.CharField(choices=[('教授', '教授'), ('副教授', '副教授'), ('讲师', '讲师'), ('青年研究员', '青年研究员'), ('其他', '其他')], default='其他', max_length=10, verbose_name='职称')),
            ],
        ),
        migrations.CreateModel(
            name='evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Com_course', models.CharField(max_length=200, verbose_name='课程评价')),
                ('Com_classroom', models.CharField(max_length=200, verbose_name='教室评价')),
                ('Com_textbook', models.CharField(max_length=200, verbose_name='教材评价')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xk_models.classinfo', verbose_name='课程id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xk_models.user', verbose_name='学生id')),
            ],
        ),
        migrations.AddField(
            model_name='classinfo',
            name='classroom',
            field=models.ManyToManyField(to='xk_models.classroom', verbose_name='教室安排'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xk_models.classdetail', verbose_name='详细信息'),
        ),
        migrations.CreateModel(
            name='classchoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(default='未发布', max_length=10, verbose_name='成绩')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xk_models.classinfo', verbose_name='课程id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xk_models.user', verbose_name='学生id')),
            ],
        ),
        migrations.AddField(
            model_name='classinfo',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xk_models.teacher', verbose_name='教师'),
        ),
    ]
