# Generated by Django 4.1.4 on 2022-12-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xk_models', '0003_alter_user_options_remove_user_c_time_user_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetail',
            name='assessment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='prerequisites',
            field=models.ManyToManyField(default=None, to='xk_models.classinfo'),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='teacher_info',
            field=models.CharField(default='', max_length=100),
        ),
    ]
