# Generated by Django 4.1.4 on 2022-12-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xk_models', '0004_classdetail_assessment_classdetail_prerequisites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetail',
            name='brief',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='exam',
            field=models.CharField(choices=[('开卷考试', '开卷考试'), ('闭卷考试', '闭卷考试'), ('半开卷考试', '半开卷考试'), ('课程论文', '课程论文'), ('其他', '其他')], default='其他', max_length=10),
        ),
        migrations.AlterField(
            model_name='classdetail',
            name='assessment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
