# Generated by Django 4.1.4 on 2022-12-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xk_models', '0006_alter_classdetail_assessment_alter_classdetail_brief_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('教授', '教授'), ('副教授', '副教授'), ('讲师', '讲师'), ('青年研究员', '青年研究员'), ('其他', '其他')], default='其他', max_length=10),
        ),
    ]
